#ABNF 1.0 UTF-8;
language zh-CN; 
mode voice;

root $main;
$main = $place1;
$place1 = 打开卫生间的灯|关闭卫生间的灯|打开客厅的灯|关闭客厅的灯|打开卧室的灯|关闭卧室的灯|打开空调|关闭空调|一小时后打开空调|一小时后关闭空调|打开电视|关闭电视|往后改台|往前改台|调大声音|调小声音|调高温度|调低温度|空调制热|空调制冷|把空调调到二十度|把空调调到二十一度|把空调调到二十二度|把空调调到二十三度|把空调调到二十四度|把空调调到二十五度|把空调调到二十六度|把空调调到二十七度|把空调调到二十八度|把空调调到二十九度|把空调调到三十度;
