#ABNF 1.0 UTF-8;
language zh-CN; 
mode voice;

root $main;
$main = $place1;
$place1 = 打开卫生间灯|关闭卫生间灯|打开客厅灯|关闭客厅灯|打开卧室灯|关闭卧室灯|打开卧室空调|关闭卧室空调|打开客厅空调|关闭客厅空调|卧室空调一小时后开启|卧室空调一小时后关闭|打开电视|关闭电视|电视频道加|电视频道减|电视音量加|电视音量减|空调温度加|空调温度减;
